version: '3.8'

services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=lucky_cali_db
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - lucky-cali

  backend:
    build: ./backend
    container_name: backend
    env_file:
      - ./backend/.env
    depends_on:
      - mariadb
    networks:
      - lucky-cali

  frontend:
    build: 
      context: ./frontend
      target: production
    container_name: frontend
    restart: unless-stopped
    networks:
      - lucky-cali
    depends_on:
      - backend


  caddy:
    build:
      context: ./caddy
      dockerfile: Dockerfile
    container_name: caddy
    environment:
      DOMAIN_NAME: ${DOMAIN_NAME}
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - lucky-cali
    depends_on:
      - backend
      - frontend

volumes:
  mariadb_data:
    driver: local
  caddy_data:
    driver: local
  caddy_config:
    driver: local
  
networks:
  lucky-cali:
    driver: bridge
