version: '3.8'

services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=lucky_cali_db
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - lucky-cali

  backend:
    build: ./backend
    container_name: backend
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/usr/src/app/backend
      - /app/node_modules
    depends_on:
      - mariadb
    networks:
      - lucky-cali

  frontend:
    build: 
      context: ./frontend
      target: development
    container_name: frontend
    restart: unless-stopped
    env_file:
      - ./frontend/.env
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - lucky-cali
    depends_on:
      - backend
    command: npm run dev -- --host

  caddy:
    image: caddy:2-alpine
    container_name: caddy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./caddy/Caddyfile.dev:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - lucky-cali
    depends_on:
      - backend
      - frontend

volumes:
  mariadb_data:
    driver: local
  caddy_data:
    driver: local
  caddy_config:
    driver: local
  
networks:
  lucky-cali:
    driver: bridge
