version: '3.8'

services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=lucky_cali_db
    ports:
      - "3307:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

  backend:
    build: ./backend
    container_name: backend
    environment:
      - DB_HOST=mariadb
      - DB_USER=root
      - DB_PASSWORD=password
      - DB_NAME=cali_db
    ports:
      - "5001:5000"
    depends_on:
      - mariadb

  frontend:
    build: ./frontend
    container_name: frontend
    depends_on:
      - backend
    ports:
      - "3000:3000"

volumes:
  mariadb_data:
    driver: local
